#!/bin/sh

# $HOME/.config/polybar/launch.sh
sh ~/.config/polybar/launch.sh
$HOME/.config/rofi/launchers/type-5/launcher.sh &

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config /home/hack/.config/picom/picom.conf  &
#pgrep -x dunst > /dev/null || dunst -conf /home/hack/.config/dunst/dunstrc &

pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
